### ISSUE TITLE
Tech Stack To Use

### ISSUE THREAD

**Issue by buttontate** [buttontate/AgOpenGPS-Server#1]
Since AgOpenGps is written in C# we should probably stay in the stack. For the web front end I would like to do React but have some experience with Angular as well.

**Comment by zpertee** [comment]
Keeping the backend on C# would be ideal for me.  I have significant backend experience (I was a senior sys admin before turning developer/architect), but am much more limited in my frontend skills (_so either javascript framework is fine by me_).

**Comment by buttontate** [comment]
@zpertee sounds good. Let me get a hello world up and we can start plugging away at initial architecture.
